name: restaurant_flutter_version
version: 1.0.0+1
publish_to: none
description: A new Flutter - Angular - Ionic project.
environment:
  sdk: '>=2.17.0-69.2.beta <3.0.0'

dependencies:
  cupertino_icons: ^1.0.4
  get: 4.6.1
  http: 0.13.4
  rxdart: 0.27.3
  url_launcher: 6.0.20
  getxfire: 0.3.3
  camera: 0.9.4+19
  path: 1.8.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

